CREATE PROCEDURE proc_listCounties() AS 	BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION RESIGNAL;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT
county_name,
county_name AS id
FROM 
county
ORDER BY
county_name ASC;

END
