CREATE PROCEDURE proc_listEcsSubsections() AS 	BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION RESIGNAL;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT
id,
name
FROM 
ecs_subsection
ORDER BY
name ASC;

END
