CREATE PROCEDURE proc_listOrderIds() AS 	BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION RESIGNAL;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT DISTINCT
order_id
FROM birds
ORDER BY
1;

END
