CREATE PROCEDURE proc_listMonthlyAverages() AS 	BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION RESIGNAL;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * 
FROM monthly_averages
WHERE
month_number > 2
ORDER BY 1;

END
